language: node_js
node_js:
    - 8

notifications:
  email: false

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

script:
    - node -v
    - npm -v
    - npm test && npm run build && echo "✅ Done"
    - ls -al dist

after_success:
  - npm run semantic-release
