language: node_js
node_js:
    - 8

notifications:
  email: false

cache:
  directories:
    - "node_modules"

jobs:
    include:
        - stage: unit tests
        - node -v
        - npm -v
        - stage: build
        - npm test && npm run build && echo "✅ Done"
        - stage: publish
        - npm run build && npm run semantic-release && echo "✅ Done"
