language: node_js
node_js:
    - 8

notifications:
  email: false

cache:
  directories:
    - "node_modules"

jobs:
    include:
        - stage: unit tests
          script: node -v
        - script: npm -v
        - stage: build
          script: npm test && npm run build && echo "✅ Done"
        - stage: publish
          script: npm run build && npm run semantic-release && echo "✅ Done"
